import { describe, expect, it } from 'vitest';
import { parseYarnLock } from '../../src/manifests/yarn-lock';
import { parsePnpmLock } from '../../src/manifests/pnpm-lock';
import { detectAndParse } from '../../src/manifests';

describe('yarn.lock（v1 / classic）', () => {
  const v1 = `# THIS IS AN AUTOGENERATED FILE.
# yarn lockfile v1


express@^4.18.0:
  version "4.18.2"
  resolved "https://registry.yarnpkg.com/express/-/express-4.18.2.tgz#abc"

"@types/node@^22.0.0":
  version "22.5.1"
  resolved "https://registry.yarnpkg.com/@types/node/-/node-22.5.1.tgz#def"

lodash@^4.17.0, lodash@~4.17.21:
  version "4.17.21"
  resolved "https://registry.yarnpkg.com/lodash/-/lodash-4.17.21.tgz#ghi"
`;

  it('パッケージ名とバージョンを取り出す', () => {
    const deps = parseYarnLock(v1);
    expect(deps.map((d) => [d.name, d.version])).toEqual([
      ['express', '4.18.2'],
      ['@types/node', '22.5.1'],
      ['lodash', '4.17.21'],
    ]);
  });

  it('ライセンスは持たないので照会対象になる', () => {
    expect(parseYarnLock(v1).every((d) => d.declaredLicense === undefined)).toBe(true);
  });

  it('同じパッケージの重複指定を1件にまとめる', () => {
    const deps = parseYarnLock(v1);
    expect(deps.filter((d) => d.name === 'lodash')).toHaveLength(1);
  });

  it('コメントと空行を無視する', () => {
    expect(parseYarnLock('# comment\n\n\n')).toEqual([]);
  });
});

describe('yarn.lock（v2+ / Berry）', () => {
  const berry = `# This file is generated by running "yarn install"
__metadata:
  version: 8

"express@npm:^4.18.0":
  version: 4.18.2
  resolution: "express@npm:4.18.2"

"@types/node@npm:^22.0.0":
  version: 22.5.1
  resolution: "@types/node@npm:22.5.1"
`;

  it('Berry 形式も解析する', () => {
    const deps = parseYarnLock(berry);
    expect(deps.map((d) => [d.name, d.version])).toEqual([
      ['express', '4.18.2'],
      ['@types/node', '22.5.1'],
    ]);
  });

  it('__metadata を依存として扱わない', () => {
    expect(parseYarnLock(berry).some((d) => d.name === '__metadata')).toBe(false);
  });
});

describe('pnpm-lock.yaml', () => {
  const pnpm = `lockfileVersion: '9.0'

packages:

  express@4.18.2:
    resolution: {integrity: sha512-abc}
    engines: {node: '>= 0.10.0'}

  '@types/node@22.5.1':
    resolution: {integrity: sha512-def}

  lodash@4.17.21:
    resolution: {integrity: sha512-ghi}
`;

  it('パッケージ名とバージョンを取り出す', () => {
    const deps = parsePnpmLock(pnpm);
    expect(deps.map((d) => [d.name, d.version])).toEqual([
      ['express', '4.18.2'],
      ['@types/node', '22.5.1'],
      ['lodash', '4.17.21'],
    ]);
  });

  it('旧形式（/name/version）も扱う', () => {
    const old = `lockfileVersion: 5.4

packages:

  /express/4.18.2:
    resolution: {integrity: sha512-abc}

  /@types/node/22.5.1:
    resolution: {integrity: sha512-def}
`;
    expect(parsePnpmLock(old).map((d) => [d.name, d.version])).toEqual([
      ['express', '4.18.2'],
      ['@types/node', '22.5.1'],
    ]);
  });

  it('peer 情報つきのキーからバージョンだけを取る', () => {
    const withPeers = `packages:

  react-dom@18.2.0(react@18.2.0):
    resolution: {integrity: sha512-x}
`;
    expect(parsePnpmLock(withPeers).map((d) => [d.name, d.version])).toEqual([
      ['react-dom', '18.2.0'],
    ]);
  });

  it('packages 節が無ければ空', () => {
    expect(parsePnpmLock("lockfileVersion: '9.0'\n")).toEqual([]);
  });
});

describe('detectAndParse が JS 系ロックファイルを見分ける', () => {
  it('yarn.lock を認識する', () => {
    const r = detectAndParse('# yarn lockfile v1\n\nexpress@^4.0.0:\n  version "4.18.2"\n');
    expect(r.ecosystem).toBe('npm');
    expect(r.dependencies[0]!.name).toBe('express');
  });

  it('pnpm-lock.yaml を認識する', () => {
    const r = detectAndParse("lockfileVersion: '9.0'\n\npackages:\n\n  express@4.18.2:\n    resolution: {integrity: sha512-x}\n");
    expect(r.ecosystem).toBe('npm');
    expect(r.dependencies[0]!.name).toBe('express');
  });
});
