import { describe, expect, it } from 'vitest';
import { parseTomlPackages } from '../../src/manifests/toml-packages';
import { parseGoSum } from '../../src/manifests/go-sum';
import { detectAndParse } from '../../src/manifests';

describe('parseTomlPackages（Cargo.lock / poetry.lock / uv.lock 共通）', () => {
  const cargo = `# This file is automatically @generated by Cargo.
version = 3

[[package]]
name = "serde"
version = "1.0.210"
source = "registry+https://github.com/rust-lang/crates.io-index"

[[package]]
name = "tokio"
version = "1.40.0"
dependencies = [
 "serde",
]
`;

  it('name と version と出所を取り出す', () => {
    // source 行を持たない 2 つめは、この Cargo.lock 自身のワークスペース
    // メンバー。crates.io を引いても無いので照会しない（tests/manifests/cargo-origin）
    expect(parseTomlPackages(cargo, 'cargo')).toEqual([
      { ecosystem: 'cargo', name: 'serde', version: '1.0.210', scope: 'runtime', origin: 'registry' },
      { ecosystem: 'cargo', name: 'tokio', version: '1.40.0', scope: 'runtime', origin: 'workspace' },
    ]);
  });

  it('poetry.lock の形式も扱う', () => {
    const poetry = `[[package]]
name = "anyio"
version = "4.14.2"
description = "High-level concurrency"
optional = false

[[package]]
name = "click"
version = "8.1.7"
`;
    expect(parseTomlPackages(poetry, 'pypi').map((d) => [d.name, d.version])).toEqual([
      ['anyio', '4.14.2'],
      ['click', '8.1.7'],
    ]);
  });

  it('入れ子のテーブルに引きずられない', () => {
    const nested = `[[package]]
name = "a"
version = "1.0.0"

[package.metadata]
name = "should-not-appear"

[[package]]
name = "b"
version = "2.0.0"
`;
    expect(parseTomlPackages(nested, 'cargo').map((d) => d.name)).toEqual(['a', 'b']);
  });

  it('version を欠くエントリは version を null にする', () => {
    const noVer = `[[package]]
name = "local-crate"
`;
    expect(parseTomlPackages(noVer, 'cargo')[0]!.version).toBeNull();
  });

  it('危険な名前を除外する', () => {
    const RTL = String.fromCharCode(0x202e);
    const bad = `[[package]]
name = "evil${RTL}x"
version = "1.0.0"

[[package]]
name = "ok"
version = "1.0.0"
`;
    expect(parseTomlPackages(bad, 'cargo').map((d) => d.name)).toEqual(['ok']);
  });

  it('重複を1件にまとめる', () => {
    const dup = `[[package]]
name = "a"
version = "1.0.0"

[[package]]
name = "a"
version = "1.0.0"
`;
    expect(parseTomlPackages(dup, 'cargo')).toHaveLength(1);
  });
});

describe('parseGoSum', () => {
  const gosum = `github.com/bytedance/gopkg v0.1.3 h1:TPBSwH8=
github.com/bytedance/gopkg v0.1.3/go.mod h1:576VvJ=
github.com/gin-gonic/gin v1.9.1 h1:abc=
github.com/gin-gonic/gin v1.9.1/go.mod h1:def=
golang.org/x/crypto v0.21.0 h1:ghi=
`;

  it('モジュールとバージョンを取り出す', () => {
    expect(parseGoSum(gosum).map((d) => [d.name, d.version])).toEqual([
      ['github.com/bytedance/gopkg', 'v0.1.3'],
      ['github.com/gin-gonic/gin', 'v1.9.1'],
      ['golang.org/x/crypto', 'v0.21.0'],
    ]);
  });

  it('/go.mod 行を重複として数えない', () => {
    expect(parseGoSum(gosum)).toHaveLength(3);
  });

  it('推移的依存を含む（go.mod より広い）', () => {
    // go.sum は直接依存だけでなく依存の依存まで記録する
    expect(parseGoSum(gosum).length).toBeGreaterThan(0);
  });

  it('空行と壊れた行を無視する', () => {
    expect(parseGoSum('\n\ngarbage\nx\n')).toEqual([]);
  });
});

describe('detectAndParse の振り分け', () => {
  it('Cargo.lock を cargo として扱う', () => {
    const r = detectAndParse('[[package]]\nname = "serde"\nversion = "1.0.210"\nsource = "registry+https://github.com/rust-lang/crates.io-index"\n');
    expect(r.ecosystem).toBe('cargo');
  });

  it('poetry.lock を pypi として扱う', () => {
    const r = detectAndParse('# This file is automatically @generated by Poetry 2.4.1\n\n[[package]]\nname = "anyio"\nversion = "4.14.2"\n');
    expect(r.ecosystem).toBe('pypi');
  });

  it('go.sum を go として扱う', () => {
    const r = detectAndParse('github.com/gin-gonic/gin v1.9.1 h1:abc=\ngithub.com/gin-gonic/gin v1.9.1/go.mod h1:def=\n');
    expect(r.ecosystem).toBe('go');
    expect(r.dependencies[0]!.name).toBe('github.com/gin-gonic/gin');
  });

  it('Cargo.toml を cargo として扱う', () => {
    const r = detectAndParse('[package]\nname = "my-app"\n\n[dependencies]\nserde = "1.0"\ntokio = { version = "1.40", features = ["full"] }\n\n[dev-dependencies]\ncriterion = "0.5"\n');
    expect(r.ecosystem).toBe('cargo');
    expect(r.dependencies.map((d) => [d.name, d.scope])).toEqual([
      ['serde', 'runtime'],
      ['tokio', 'runtime'],
      ['criterion', 'dev'],
    ]);
  });
});
