import { isSafePackageName } from './name-safety';
import type { Dependency, Ecosystem } from '../types';

/**
 * TOML の `[[package]]` 配列から name と version を取り出す。
 *
 * Cargo.lock・poetry.lock・uv.lock はいずれもこの形をしている。
 * 完全な TOML パーサは要らない。必要なのは配列テーブルの直下にある
 * 2 つのキーだけで、そのために依存を増やす理由に乏しい。
 *
 * いずれもライセンスを内包しないため、解決には上流照会か共有キャッシュが要る。
 */
export function parseTomlPackages(content: string, ecosystem: Ecosystem): Dependency[] {
  const found = new Map<string, string | null>();

  let inPackage = false;
  let name: string | null = null;
  let version: string | null = null;

  const flush = () => {
    if (name !== null && isSafePackageName(name) && !found.has(name)) {
      found.set(name, version);
    }
    name = null;
    version = null;
  };

  for (const raw of content.split(/\r?\n/)) {
    const line = raw.trim();
    if (line === '' || line.startsWith('#')) continue;

    if (line === '[[package]]') {
      flush();
      inPackage = true;
      continue;
    }

    // 別のテーブルが始まったら package 節の外。[package.metadata] なども含む
    if (line.startsWith('[')) {
      flush();
      inPackage = false;
      continue;
    }

    if (!inPackage) continue;

    const m = /^(name|version)\s*=\s*"([^"]*)"\s*$/.exec(line);
    if (!m) continue;
    if (m[1] === 'name') name = m[2]!;
    else version = m[2]!;
  }
  flush();

  return [...found].map(([n, v]) => ({
    ecosystem,
    name: n,
    version: v,
    scope: 'runtime' as const,
  }));
}

/** Cargo.lock か（poetry / uv と区別するため source を見る） */
export function isCargoLock(content: string): boolean {
  return /^\[\[package\]\]/m.test(content) && /crates\.io-index|^\s*checksum\s*=/m.test(content);
}

/** poetry.lock / uv.lock か */
export function isPythonLock(content: string): boolean {
  return (
    /^\[\[package\]\]/m.test(content) &&
    (/@generated by Poetry/i.test(content) ||
      /^\s*python-versions\s*=/m.test(content) ||
      /requires-python/.test(content))
  );
}
